name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew (Admin App)
      run: chmod +x Admin/gradlew
    - name: Build with Gradle
      run: cd Admin && ./gradlew build
    - name: Run Tests (Admin App)
      run: cd Admin && ./gradlew test
    # - name: Upload a Build Artifact (Admin App)
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: Cinecomplex_Admin
    #     path: Admin/app/build/outputs/apk/debug/app-debug.apk
    - name: Build Release APK (Admin)
      run: ./gradlew assembleRelease
    - name: Publish APK (Admin)
      uses: alsrb968/action-release-apk@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        APP_FOLDER: app
        
    - name: Grant execute permission for gradlew (Manager App)
      run: chmod +x Manager/gradlew
    - name: Build with Gradle
      run: cd Manager && ./gradlew build
    - name: Run Tests (Manager App)
      run: cd Manager && ./gradlew test
    # - name: Upload a Build Artifact (Manager App)
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: Cinecomplex_Manager
    #     path: Manager/app/build/outputs/apk/debug/app-debug.apk
    - name: Build Release APK (Manager)
      run: ./gradlew assembleRelease
    - name: Publish APK (Manager)
      uses: alsrb968/action-release-apk@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        APP_FOLDER: app

    - name: Grant execute permission for gradlew (User App)
      run: chmod +x User/gradlew
    - name: Create local.properties with SDK location
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
    - name: Build with Gradle
      run: cd User && ./gradlew build
    - name: Run Tests (User App)
      run: cd User && ./gradlew test
    # - name: Upload a Build Artifact (User App)
    #   uses: actions/upload-artifact@v4.3.3
    #   with:
    #     name: Cinecomplex_User
    #     path: User/app/build/outputs/apk/debug/app-debug.apk
    - name: Build Release APK (User)
      run: ./gradlew assembleRelease
    - name: Publish APK (User)
      uses: alsrb968/action-release-apk@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        APP_FOLDER: app
    
